### ISSUE TITLE
build fail about ppx_pattern_bind

### ISSUE THREAD

**Issue by phstrauss** [janestreet/bonsai#1]
Hello,

despite having installed all required dependencies (via opam, packages of the day :-), including ppx_pattern_bind, bonsai build fail.
I'm on a 4.09.0 switch :

opam install bonsai
The following actions will be performed:
  ∗ install bonsai v0.13.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[bonsai.v0.13.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The compilation of bonsai failed at "/Users/philou/.opam/opam-init/hooks/sandbox.sh build dune build -p bonsai
        -j 4".

#=== ERROR while compiling bonsai.v0.13.0 =====================================#
# context     2.0.5 | macos/x86_64 | ocaml-base-compiler.4.09.0 | https://opam.ocaml.org/#53a3f342
# path        ~/.opam/4.09.0/.opam-switch/build/bonsai.v0.13.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p bonsai -j 4
# exit-code   1
# env-file    ~/.opam/log/bonsai-60014-d2c37b.env
# output-file ~/.opam/log/bonsai-60014-d2c37b.out
### output ###
# File "src/dune", line 4, characters 16-32:
# 4 |   (pps ppx_jane ppx_pattern_bind -annotated-ignores -check-doc-comments))
#                     ^^^^^^^^^^^^^^^^
# Error: Library "ppx_pattern_bind" not found.
# Hint: try: dune external-lib-deps --missing -p bonsai -j 4 @@default

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build bonsai v0.13.0
└─ 
╶─ No changes have been performed

philou@air:~/Sources/Repos/OCAML/bonsai-git$ opam list | grep ppx_pattern_bind
ppx_pattern_bind        v0.13.0      A ppx for writing fast incremental bind nodes in a pattern match

philou@air:~/Sources/Repos/OCAML/bonsai-git$ dune build
File "src/dune", line 4, characters 16-32:
4 |   (pps ppx_jane ppx_pattern_bind -annotated-ignores -check-doc-comments))
                    ^^^^^^^^^^^^^^^^
Error: Library "ppx_pattern_bind" not found.
Hint: try: dune external-lib-deps --missing @@default

**Comment by phstrauss** [comment]
my ppx_pattern_bind v0.13 opam install of the day is empty, it contains an empty META file, a basic dune file and an opam file, no ml mli cm*

**Comment by xclerc** [comment]
This issue should be fix by the upcoming release of
`ppx_pattern_bind` (https://github.com/ocaml/opam-repository/pull/15358).

**Comment by xclerc** [comment]
(Fixed by https://github.com/ocaml/opam-repository/pull/15358.)
