### ISSUE TITLE
Missing dependency: ocaml-embed-file

### ISSUE THREAD

**Issue by Strikeskids** [janestreet/bonsai#13]
The library `examples/open_source/rpc_chat/server` depends on this package to include the javascript file in the server. Trying to `opam install bonsai` without having this `ocaml-embed-file` already installed fails.

**Comment by TyOverby** [comment]
the examples aren't used to calculate the dependencies for the library.  Otherwise, if people downloaded "bonsai" they'd also get things that they don't necessarily need.

**Comment by Strikeskids** [comment]
Why am I unable to install bonsai without having already installed ocaml-embed-file then? I think that putting the `(public_name bonsai.example_chat_open_source_native)` config causes it to be a part of the bonsai package.

**Comment by aalekseyev** [comment]
This should be fixed now.
