### ISSUE TITLE
`src/proc.mli` is missed, but referenced in `README.md`

### ISSUE THREAD

**Issue by prekel** [janestreet/bonsai#18]
`src/proc.mli` is referenced in [README.md](https://github.com/janestreet/bonsai/blob/d42f19ba7fd17b8363408f11da181a3812fa6c81/README.md) and [Homepage](https://opensource.janestreet.com/bonsai/), but not found. 
It was removed at https://github.com/janestreet/bonsai/commit/2619a3a5cafb94a57a80cdefc83da1b5c0e182c7#diff-ea1e3795894f1ff003f30ffa0cccdeb94af7b828151086be2ab8ef4ade2ec2cf

**Comment by aalekseyev** [comment]
Fixed
