### ISSUE TITLE
dune build --profile=release fails at compiling web/examples

### ISSUE THREAD

**Issue by phstrauss** [janestreet/bonsai#2]
Hello bonsai dev (xclerc?)

I wanted to give a try to the --profile=release switch of dune, thinking it would help reduce the size of the generated js. And it bombs in a strange manner, mixing file of two different switch : I'm on a plain 4.09.0 switch doing bonsai tryout, and it prints error about 4.09.0 AND 4.02.3 shared object files!!

Regards

```
philou@air:~/mysrc/tmp/hello-world$ dune build ./hello_world.bc.js
philou@air:~/mysrc/tmp/hello-world$ ls _build/default/
...               11272 hello_world.bc.js      ...
philou@air:~/mysrc/tmp/hello-world$ dune clean
philou@air:~/mysrc/tmp/hello-world$ dune build --profile=release ./hello_world.bc.js
File "_none_", line 1:
Error: Error on dynamically loaded library: /Users/philou/.opam/4.09.0/lib/stublibs/dllcore_kernel_stubs.so: dlopen(/Users/philou/.opam/4.09.0/lib/stublibs/dllcore_kernel_stubs.so, 10): Symbol not found: _caml_stat_heap_size
  Referenced from: /Users/philou/.opam/4.02.3/lib/stublibs/dllcore_kernel_stubs.so
  Expected in: flat namespace
 in /Users/philou/.opam/4.02.3/lib/stublibs/dllcore_kernel_stubs.so
```

**Comment by phstrauss** [comment]
philou@air:~/.opam/4.02.3/lib/stublibs$ nm dllcore_kernel_stubs.so | grep -i stat
                 U _caml_stat_compactions
                 U _caml_stat_heap_chunks
                 U _caml_stat_heap_size
                 U _caml_stat_major_collections
                 U _caml_stat_major_words
                 U _caml_stat_minor_collections
                 U _caml_stat_minor_words
                 U _caml_stat_promoted_words
                 U _caml_stat_top_heap_size

philou@air:~/.opam/4.09.0/lib/stublibs$ nm dllcore_kernel_stubs.so | grep -i stat
                 U _caml_stat_compactions
                 U _caml_stat_heap_chunks
                 U _caml_stat_heap_wsz
                 U _caml_stat_major_collections
                 U _caml_stat_major_words
                 U _caml_stat_minor_collections
                 U _caml_stat_minor_words
                 U _caml_stat_promoted_words
                 U _caml_stat_top_heap_wsz

I'm on macOS X 10.11.6

philou@air:~/.opam/4.09.0/lib/stublibs$ cc -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by TyOverby** [comment]
I don't have access to OS-X, so I'm trying to repro on Linux.

So far: 

4.08.0 -> no error
4.09.0 -> still compiling...

**Comment by TyOverby** [comment]
@phstrauss: The fact that you have a 4.02 file being referenced from a 4.09 project is concerning and points to an incorrectly configured opam.  

Could you try opening bash without an RC file `bash --noprofile --norc`, and then calling `opam switch 4.09.0` from that environment.

**Comment by phstrauss** [comment]
oh yes, their something weird going on:

philou@air:~$ opam switch
  switch  compiler                    description
   4.02.3  ocaml-base-compiler.4.02.3  base-bigarray.base base-ocamlbuild.base base-threads.base base-unix.base
                                       ocaml-base-compiler.4.02.3
→  4.07.1  ocaml-base-compiler.4.07.1  4.07.1
   4.09.0  ocaml-base-compiler.4.09.0  4.09.0
   system  ocaml-system.system

philou@air:~$ bash --noprofile --norc
bash-3.2$ opam switch 4.09.0
bash-3.2$ env
CAML_LD_LIBRARY_PATH=/Users/philou/.opam/4.07.1/lib/stublibs:/Users/philou/.opam/4.07.1/lib/ocaml/stublibs:/Users/philou/.opam/4.07.1/lib/ocaml
MANPATH=/opt/local/share/man
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/kb/vsqp5c4917x_6tm36k6tvw340000gn/T/
MYSRC_BASE=/Users/philou/mysrc
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.oGkXb52SqD/Render
TERM_PROGRAM_VERSION=361.2
TERM_SESSION_ID=E423FEF1-D429-447B-B68C-CD26BAC9F6CE
OPAM_SWITCH_PREFIX=/Users/philou/.opam/4.07.1
OCAML_TOPLEVEL_PATH=/Users/philou/.opam/4.07.1/lib/toplevel
USER=philou
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.zFbJj7BdkP/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x1
PATH=/Users/philou/.opam/4.07.1/bin:/Users/philou/bin:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/Pkgs/capnproto-c++/0.7.0/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
PWD=/Users/philou
LANG=fr_CH.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=2
HOME=/Users/philou
GTK_PATH=/opt/local/lib/gtk-2.0:/opt/local/lib/gtk-3.0
LOGNAME=philou
PKG_CONFIG_PATH=:/usr/local/share/pkgconfig/
DISPLAY=/private/tmp/com.apple.launchd.BMqTkOjb76/org.macosforge.xquartz:0
OPAMNOENVNOTICE=true
_=/usr/bin/env
bash-3.2$ 

I'm using opam 2.0.5 from macports :

bash-3.2$ port installed | grep opam
  opam @2.0.5_1 (active)

**Comment by phstrauss** [comment]
```
bash-3.2$ opam switch
  switch  compiler                    description
   4.02.3  ocaml-base-compiler.4.02.3  base-bigarray.base base-ocamlbuild.base base-threads.base base-unix.base
                                       ocaml-base-compiler.4.02.3
   4.07.1  ocaml-base-compiler.4.07.1  4.07.1
→  4.09.0  ocaml-base-compiler.4.09.0  4.09.0
   system  ocaml-system.system
bash-3.2$ which ocaml
/Users/philou/.opam/4.07.1/bin/ocaml
bash-3.2$ ocaml
        OCaml version 4.07.1
```

**Comment by phstrauss** [comment]
```
bash-3.2$ pwd
/Users/philou/mysrc/tmp/time
bash-3.2$ dune clean
bash-3.2$ ls
dune		dune-project	hello_world.ml	hello_world.mli	index.html
bash-3.2$ dune build ./hello_world.bc.js
Error: Library js_of_ocaml-compiler not found
 (context: default)
Hint: try: opam install js_of_ocaml-compiler
File "dune", line 2, characters 18-26:
2 |  (preprocess (pps ppx_jane)))
                      ^^^^^^^^
Error: Library "ppx_jane" not found.
Hint: try: dune external-lib-deps --missing ./hello_world.bc.js

bash-3.2$ opam list | grep jane
jane-street-headers     v0.13.0      Jane Street C header files
ppx_jane                v0.13.0      Standard Jane Street ppx rewriters
bash-3.2$ ocamlfind list | grep jane
bash-3.2$ 
```

**Comment by hhugo** [comment]
```
opam list -a | grep ppx_jane
ppx_jane                           --          Standard Jane Street ppx rewriters
```
Please install ppx_jane and the js_of_ocaml-compiler

`opam install ppx_jane js_of_ocaml-compiler`

**Comment by phstrauss** [comment]
```
bash-3.2$ opam install ppx_jane js_of_ocaml-compiler
[NOTE] Package js_of_ocaml-compiler is already installed (current version is 3.5.1).
[NOTE] Package ppx_jane is already installed (current version is v0.13.0).
```

**Comment by phstrauss** [comment]
I still have this one in my .bash_profile : 
`. /Users/philou/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true`
Is it still current using opam 2.0.5 ?

**Comment by phstrauss** [comment]
I did the following and it happens to build on release profile fine!!

```
philou@air:~$ opam switch 4.09.0
philou@air:~$ bash --noprofile --norc
bash-3.2$ opam switch 4.09.0
bash-3.2$ env
CAML_LD_LIBRARY_PATH=/Users/philou/.opam/4.09.0/lib/stublibs:/Users/philou/.opam/4.09.0/lib/ocaml/stublibs:/Users/philou/.opam/4.09.0/lib/ocaml
MANPATH=/opt/local/share/man
TERM_PROGRAM=Apple_Terminal
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/kb/vsqp5c4917x_6tm36k6tvw340000gn/T/
MYSRC_BASE=/Users/philou/mysrc
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.oGkXb52SqD/Render
TERM_PROGRAM_VERSION=361.2
TERM_SESSION_ID=C256F6DE-2753-4C63-AD21-F1B53E338650
OPAM_SWITCH_PREFIX=/Users/philou/.opam/4.09.0
OCAML_TOPLEVEL_PATH=/Users/philou/.opam/4.09.0/lib/toplevel
USER=philou
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.zFbJj7BdkP/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x1
PATH=/Users/philou/.opam/4.09.0/bin:/Users/philou/bin:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/Pkgs/capnproto-c++/0.7.0/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
PWD=/Users/philou
LANG=fr_CH.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
HOME=/Users/philou
SHLVL=2
GTK_PATH=/opt/local/lib/gtk-2.0:/opt/local/lib/gtk-3.0
LOGNAME=philou
PKG_CONFIG_PATH=:/usr/local/share/pkgconfig/
DISPLAY=/private/tmp/com.apple.launchd.BMqTkOjb76/org.macosforge.xquartz:0
OPAMNOENVNOTICE=true
_=/usr/bin/env
bash-3.2$ 
bash-3.2$ cd mysrc/tmp/time
bash-3.2$ dune clean
bash-3.2$ dune build --profile=release ./hello_world.bc.js
bash-3.2$ ls -altr _build/default/
total 92752
drwxr-xr-x  3 philou  staff       102 27 nov 19:53 .ppx
-rw-r--r--  1 philou  staff         0 27 nov 19:53 .merlin-exists
-rw-r--r--  1 philou  staff      7340 27 nov 19:53 .merlin
-rw-r--r--  1 philou  staff       331 27 nov 19:53 hello_world.ml
-rw-r--r--  1 philou  staff       867 27 nov 19:53 hello_world.pp.mli
-rw-r--r--  1 philou  staff      2361 27 nov 19:53 hello_world.pp.ml
-rw-r--r--  1 philou  staff        45 27 nov 19:53 hello_world.mli
drwxr-xr-x  3 philou  staff       238 27 nov 19:53 .hello_world.eobjs
-rwxr-xr-x  1 philou  staff  46513032 27 nov 19:53 hello_world.bc
-rw-r--r--  1 philou  staff    946640 27 nov 19:54 hello_world.bc.js
drwxr-xr-x  3 philou  staff       272 27 nov 19:54 ..
drwxr-xr-x  4 philou  staff       408 27 nov 19:54 .
```

**Comment by TyOverby** [comment]
great!
