### ISSUE TITLE
History.md seems to be outdated; it seems that proc.md is newer and not mentioned

### ISSUE THREAD

**Issue by mlemerre** [janestreet/bonsai#23]
Hello,

I am trying to understand how bonsai works, but there are several generations of APIs that coexist in the docs and this makes things a bit difficult to grab.

It seems to me that the API defined in the proc.md file describes the newest API (at least it seems to be cleaner) so it may be worth it to refer to it in history.md, so that it is easier to understand what is outdated and what is more current?

Thanks
Matthieu

**Comment by aalekseyev** [comment]
Fixed, ostensibly
