### ISSUE TITLE
Text in getting_started/counters.mdx doesn't match the code

### ISSUE THREAD

**Issue by fhars** [janestreet/bonsai#25]
The description for `counter_component` says "for that, we use `()`", which is actually never used in the code snippet, and if you try to "Notice the module inclusion via `module Model = Model`" in `add_counter_component`, you will mostly notice its absence.

Both seem to have been removed with https://github.com/janestreet/bonsai/commit/227499d537f33696bfa4371f9162ca9eba7f0f5f

**Comment by staronj** [comment]
I believe this has now been fixed internally. The fix will land on the main branch soon.
