### ISSUE TITLE
How to build rpc_chat example?

### ISSUE THREAD

**Issue by dboris** [janestreet/bonsai#3]
Trying to build the rpc_chat client:
```
File "web/examples/rpc_chat/client/dune", line 2, characters 25-38:
2 |  (libraries async_kernel async_js_jane core_kernel bonsai_web
                             ^^^^^^^^^^^^^
Error: Library "async_js_jane" not found.
Hint: try: dune external-lib-deps --missing ./main.bc.js

phantom:client boris$ dune external-lib-deps --missing ./main.bc.js
Error: The following libraries are missing in the default context:
- async_js_jane
- vdom_input_widgets
Hint: try: opam install async_js_jane vdom_input_widgets

phantom:client boris$ opam install async_js_jane vdom_input_widgets
[ERROR] No package named async_js_jane found.
[ERROR] No package named vdom_input_widgets found.
```

What package do I need to install?

**Comment by TyOverby** [comment]
Sadly, `async_js_jane` has not been open-sourced yet.  There are plans to do so, but it will be a long time.  

I should probably remove this example from the public repo.

**Comment by hhugo** [comment]
One can trivially fix the code using `async_js` instead of `async_js_jane`

**Comment by TyOverby** [comment]
Ah yes, that's correct.  Sorry; I was thinking about the server-side of the websocket communication not being open-source.  Indeed, in `web/examples/rpc_chat/server/src/dune`, the `cohttp_static_handler` and `simple_web_server` libraries are not open source.

**Comment by TyOverby** [comment]
I'm closing this because we currently don't have any plans for open-sourcing the server-side code.
