### ISSUE TITLE
Last version of bonsai makes the hello world example not compilable

### ISSUE THREAD

**Issue by mattiasdrp** [janestreet/bonsai#39]
Hi :-)

```
❯ dune build ./main.bc.js
Entering directory '/home/mattias/bonsai'
File "ppx_bonsai/src/expander/ppx_bonsai_expander.ml", line 55, characters 56-59:
55 |            sub_return ~loc ~modul ~lhs:(ppat_any ~loc) ~rhs ~body
                                                             ^^^
Error: This expression has type prevent_tail_call:bool -> expression
       but an expression was expected of type expression
```

I added the janestreet opam repository and installed everything from an empty opam switch because otherwise I had this error:
```

❯ dune build ./main.bc.js
Entering directory '/home/mattias/bonsai'
File "src/dune", line 3, characters 19-42:
3 |   incr_dom.ui_incr incr_dom.ui_time_source tailwind_colors)
                       ^^^^^^^^^^^^^^^^^^^^^^^
Error: Library "incr_dom.ui_time_source" not found.
-> required by library "bonsai" in _build/default/src
-> required by executable main in examples/hello_world/dune:1
-> required by _build/default/examples/hello_world/main.bc.js
```

The bonsai version was 0.16.

The new version is:

> bonsai                      v0.17~preview.128.39+57

Have a nice day and thanks for this package :-)

**Comment by TyOverby** [comment]
How long ago did you download the bonsai repository? k

**Comment by mattiasdrp** [comment]
I downloaded the bonsai repository yesterday so it's on [this commit](https://github.com/janestreet/bonsai/commit/93ca7ce40d0bf559ef9a7a3f3496890bdf799739). And I installed the new opam switch the exact same day. I see that there's a new commit now, I'll try with it.

**Comment by mattiasdrp** [comment]
The latest commit fixed it, thanks :-)

**Comment by TyOverby** [comment]
Ha wow you got really unlucky!

**Comment by mattiasdrp** [comment]
Yep 😂 
I downloaded the package just before it was updated. Thanks for pointing me to the proper fix :-)
