### ISSUE TITLE
Bonsai_web missing from opam, bonsai has incorrect dependencies list

### ISSUE THREAD

**Issue by TyOverby** [janestreet/bonsai#4]
I would expect “bonsai” opam package to have only the dependencies listed in `src/dune`, and for the dune project inside of the `bonsai_web` subdirectory to be published as well.

**Comment by xclerc** [comment]
My understanding is that `bonsai_web` is indeed part of the `bonsai`
package because its public name is `bonsai.web`.

If we want `bonsai_web` to be independent, we should set its public
name to *e.g.* `bonsai_web`.

**Comment by TyOverby** [comment]
> If we want bonsai_web to be independent, we should set its public name to e.g. bonsai_web.

Can we do this and keep them both in the same github repository?
