### ISSUE TITLE
"Getting Started" missing

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [janestreet/bonsai#6]
I wanted to give Bonsai a try to see how it works and there is a link to a "getting started" document which sounded interesting, unfortunately that leads to a 404 since that documentation does not seem to be on GitHub.

Could you please add it? TIA!

**Comment by xclerc** [comment]
(Addressed by https://github.com/janestreet/bonsai/commit/6e62a5a6d9fdc621cd5cf2ac8d264720829814d2.)
